'use strict';
// Exercise the real packaged Windows host in an isolated, persistent test profile.
const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { spawn } = require('node:child_process');
const ROOT = path.resolve(__dirname, '..');
const exe = path.join(ROOT, 'dist', `ZERO-win32-${process.arch}`, 'ZERO.exe');
const results = [];
async function main() {
  const profile = await fs.mkdtemp(path.join(ROOT, 'dist', 'qa-profile-'));
  const shots = path.join(ROOT, 'dist', 'qa');
  await fs.mkdir(shots, { recursive: true });
  let host;
  const errors = [];
  const check = (name, value) => { assert.ok(value, name); results.push(name); console.log(`PASS ${name}`); };
  const start = async () => {
    const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
    host = await electron.launch({ executablePath: exe, args: [`--user-data-dir=${profile}`], env });
    const page = await host.firstWindow();
    page.on('pageerror', error => errors.push(error.message));
    await page.waitForSelector('body.native #timer');
    await page.waitForTimeout(600);
    return page;
  };
  const nativeWindow = () => host.evaluate(({ BrowserWindow }) => {
    const w = BrowserWindow.getAllWindows()[0];
    return { pinned: w.isAlwaysOnTop(), visible: w.isVisible(), bounds: w.getBounds() };
  });
  try {
    let page = await start();
    check('packaged app loads sandboxed native renderer', await host.evaluate(({ app, BrowserWindow }) => app.isPackaged && BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences().sandbox));
    check('starts always on top', (await nativeWindow()).pinned);
    await host.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setAlwaysOnTop(false));
    await page.waitForTimeout(2300);
    check('recovers topmost after another window manager clears it', (await nativeWindow()).pinned);
    const compact = await page.locator('#widget').boundingBox();
    console.log('Compact bounds:', compact);
    await page.screenshot({ path: path.join(shots, 'compact.png') });
    check('compact observatory fits 280 by 300 pixels', compact.width <= 280 && compact.height <= 300);
    check('compact view includes IJburg temperature', await page.locator('#localTemperature').isVisible() && (await page.locator('#weatherLocation').innerText()).includes('IJburg'));
    check('one unified canvas and real wind units lead the compact instruments', await page.locator('#unifiedCanvas').isVisible() && (await page.locator('.unified-readings').innerText()).includes('mHz') && !await page.locator('#waveform').isVisible());
    await page.locator('#weatherToggle').click();
    check('weather details disclose model temperature and its source time', (await page.locator('#weatherDetails').innerText()).includes('2 m above ground') && await page.locator('#weatherTimestamp').isVisible());
    await page.locator('#weatherClose').click();
    check('population leads the display and keeps a secondary timer', (await page.locator('#population').boundingBox()).y < (await page.locator('#timer').boundingBox()).y);
    const initialPopulation = await page.locator('#population').innerText();
    await page.waitForTimeout(1100);
    check('population keeps counting independently of the paused timer', await page.locator('#population').innerText() !== initialPopulation && await page.locator('#timer').innerText() === '25:00');
    await page.screenshot({ path: path.join(shots, 'compact.png') });
    await page.locator('#startButton').click();
    await page.waitForTimeout(1300);
    check('timer runs and energy accumulates', await page.locator('#timer').innerText() !== '25:00' && await page.locator('#energy').innerText() !== '0.00 J');
    await page.locator('#closeButton').click();
    check('close hides without destroying the timer', !(await nativeWindow()).visible);
    await page.waitForTimeout(1200);
    await host.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.send('zero:action', 'toggle-timer'));
    const paused = await page.locator('#timer').innerText();
    await page.waitForTimeout(1100);
    check('tray pause action works while hidden', await page.locator('#timer').innerText() === paused && await page.locator('#startText').innerText() === 'Resume');
    const duplicate = spawn(exe, [`--user-data-dir=${profile}`], { stdio: 'ignore', windowsHide: true });
    await new Promise((resolve, reject) => { duplicate.once('exit', resolve); duplicate.once('error', reject); });
    await page.waitForTimeout(400);
    check('second launch restores the existing window', (await nativeWindow()).visible && await host.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length) === 1);
    await page.locator('#floatButton').click();
    check('pin toggle changes actual native window state', !(await nativeWindow()).pinned);
    await page.waitForTimeout(2300);
    check('explicit unpin stays unpinned', !(await nativeWindow()).pinned);
    await page.locator('#floatButton').click();
    await page.locator('#compactButton').click();
    await page.waitForTimeout(500);
    const expanded = await page.locator('#widget').boundingBox();
    check('expanded view keeps the unified field and collapsed model controls', expanded.width === 560 && expanded.height <= 760 && await page.locator('#unifiedCanvas').isVisible() && !await page.locator('#expertPanel').getAttribute('open'));
    await page.screenshot({ path: path.join(shots, 'expanded.png') });
    await page.locator('#expertPanel > summary').click();
    await page.locator('#probeInput').evaluate(el => {el.value='-200';el.dispatchEvent(new Event('input',{bubbles:true}));});
    check('signed distance places a below-population probe on the negative side', (await page.locator('#distanceValue').innerText()).includes('−'));
    await page.locator('#tareButton').click();
    check('tare resets the probe offset and retains the live counter', await page.locator('#probeInput').inputValue() === '0' && await page.locator('#population').innerText() !== '0');
    await page.locator('[data-coupling=dc]').click();
    check('DC coupling includes the offset and shows calibrated meter units', (await page.locator('#scopeMode').innerText()).startsWith('DC') && !(await page.locator('#meterAC').innerText()).includes('NaN'));
    await page.locator('[data-coupling=ac]').click();
    await page.locator('#radarTab').click();
    await page.locator('#radarRangeInput').evaluate(el => {el.value='80';el.dispatchEvent(new Event('input',{bubbles:true}));});
    await page.locator('#radarSpeedInput').evaluate(el => {el.value='-5';el.dispatchEvent(new Event('input',{bubbles:true}));});
    await page.waitForTimeout(400);
    check('virtual radar responds to range and signed velocity', (await page.locator('#radarRange').innerText()).includes('80.0') && (await page.locator('#radarDoppler').innerText()).includes('−'));
    await page.locator('#toast').waitFor({ state: 'hidden' });
    await page.screenshot({ path: path.join(shots, 'radar.png') });
    await page.locator('#radarFreezeButton').click();
    await page.waitForTimeout(1100);
    const radarFrozen = await page.locator('#radarMap').evaluate(el => el.toDataURL());
    const countBeforeFreeze = await page.locator('#population').innerText();
    await page.waitForTimeout(1100);
    check('freeze holds instrument animation while population remains live', radarFrozen === await page.locator('#radarMap').evaluate(el => el.toDataURL()) && countBeforeFreeze !== await page.locator('#population').innerText());
    await page.locator('#radarFreezeButton').click();
    await page.locator('#telemetryTab').click();
    await page.waitForTimeout(500);
    check('Earth-space panel exposes Bayer atlas and independent observation timestamps', await page.locator('#bayerAtlas').isVisible() && await page.locator('#noaaTimestamp').isVisible());
    await page.screenshot({ path: path.join(shots, 'earth-space.png') });
    await page.locator('#telemetryPanel').screenshot({ path: path.join(shots, 'telemetry-panel.png') });
    await page.locator('[data-instrument=signal]').click();
    await page.locator('#settingsButton').click();
    check('native desktop settings are present', await page.locator('#launchAtLoginInput').isVisible() && await page.locator('#pinnedInput').isChecked());
    await page.locator('[name=focusMinutes]').fill('30');
    await page.locator('button[type=submit]').click();
    await page.locator('#resetButton').click();
    check('new focus duration applies on reset', await page.locator('#timer').innerText() === '30:00');
    await page.locator('[data-mode=short]').click();
    check('short break has distinct phase', await page.locator('#timer').innerText() === '05:00' && await page.locator('#phaseLabel').innerText() === 'SHORT BREAK');
    await page.locator('#skipButton').click();
    check('skip returns to focus without counting a completion', await page.locator('#timer').innerText() === '30:00' && await page.locator('#sessionLabel').innerText() === '0 COMPLETE');
    await page.locator('#compactButton').click();
    await page.waitForTimeout(500);
    await page.locator('#settingsButton').click();
    await page.waitForTimeout(500);
    await page.locator('#toast').waitFor({ state: 'hidden' });
    await page.screenshot({ path: path.join(shots, 'settings.png') });
    const drawer = await page.locator('#widget').boundingBox();
    check('compact settings expand to a readable panel', drawer.width === 440 && drawer.height >= 570);
    await page.keyboard.press('Escape');
    await page.waitForTimeout(500);
    await host.evaluate(({ BrowserWindow, screen }) => {
      const w = BrowserWindow.getAllWindows()[0], a = screen.getDisplayMatching(w.getBounds()).workArea;
      w.setPosition(a.x + 90, a.y + 90);
    });
    await page.waitForTimeout(600);
    const moved = (await nativeWindow()).bounds;
    await page.locator('#startButton').click();
    await page.waitForTimeout(1200);
    await page.locator('#startButton').click();
    const savedTime = await page.locator('#timer').innerText();
    await host.close(); host = null;
    page = await start();
    const restored = (await nativeWindow()).bounds;
    check('window position survives relaunch', restored.x === moved.x && restored.y === moved.y);
    check('paused timer and settings survive relaunch', await page.locator('#timer').innerText() === savedTime && await page.locator('#startText').innerText() === 'Resume');
    check('pin state survives relaunch', (await nativeWindow()).pinned);
    check('no renderer exceptions', errors.length === 0);
    await fs.writeFile(path.join(shots, 'desktop-results.json'), JSON.stringify({ date: new Date().toISOString(), checks: results, errors, compact, expanded }, null, 2));
  } finally { if (host) await host.close(); }
  console.log(`${results.length} real Electron checks passed.`);
}
main().catch(error => { console.error(error); process.exitCode = 1; });
